"""add docket grading spine: pick, prediction, week result, game scores

Revision ID: 04298e2415e9
Revises: 39cbbef16b24
Create Date: 2026-08-11 21:30:35.250932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04298e2415e9'
down_revision = '39cbbef16b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docket_tiebreaker_prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('prediction_tenths', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['docket_week.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_id', name='uq_docket_prediction_user_week')
    )
    with op.batch_alter_table('docket_tiebreaker_prediction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docket_tiebreaker_prediction_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_docket_tiebreaker_prediction_week_id'), ['week_id'], unique=False)

    op.create_table('docket_week_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('error_tenths', sa.Integer(), nullable=False),
    sa.Column('is_dropped', sa.Boolean(), nullable=False),
    sa.Column('graded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['docket_week.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_id', name='uq_docket_week_result_user_week')
    )
    with op.batch_alter_table('docket_week_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docket_week_result_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_docket_week_result_week_id'), ['week_id'], unique=False)

    op.create_table('docket_pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('is_best', sa.Boolean(), nullable=False),
    sa.Column('is_autopick', sa.Boolean(), nullable=False),
    sa.Column('line_value', sa.Float(), nullable=False),
    sa.Column('book', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('NOT (is_best AND slot = 9)', name='ck_docket_pick_best_not_backup'),
    sa.CheckConstraint('slot >= 1 AND slot <= 9', name='ck_docket_pick_slot_range'),
    sa.ForeignKeyConstraint(['game_id'], ['docket_game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['docket_week.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_id', 'game_id', 'market', name='uq_docket_pick_one_side_per_market'),
    sa.UniqueConstraint('user_id', 'week_id', 'slot', name='uq_docket_pick_slot')
    )
    with op.batch_alter_table('docket_pick', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docket_pick_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_docket_pick_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_docket_pick_week_id'), ['week_id'], unique=False)
        batch_op.create_index('uq_docket_pick_best_per_user_week', ['user_id', 'week_id'], unique=True, sqlite_where=sa.text('is_best'), postgresql_where=sa.text('is_best'))

    # NOT NULL booleans carry a server_default so the existing docket_game
    # rows (90 imported Week 1 games in prod) backfill to False instead of
    # failing the ALTER (repo precedent: 8c282ed0beac, 683bff36f66e).
    with op.batch_alter_table('docket_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_final', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
        batch_op.add_column(sa.Column('no_contest', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
        batch_op.add_column(sa.Column('nc_reason', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docket_game', schema=None) as batch_op:
        batch_op.drop_column('nc_reason')
        batch_op.drop_column('no_contest')
        batch_op.drop_column('is_final')
        batch_op.drop_column('away_score')
        batch_op.drop_column('home_score')

    with op.batch_alter_table('docket_pick', schema=None) as batch_op:
        batch_op.drop_index('uq_docket_pick_best_per_user_week', sqlite_where=sa.text('is_best'), postgresql_where=sa.text('is_best'))
        batch_op.drop_index(batch_op.f('ix_docket_pick_week_id'))
        batch_op.drop_index(batch_op.f('ix_docket_pick_user_id'))
        batch_op.drop_index(batch_op.f('ix_docket_pick_game_id'))

    op.drop_table('docket_pick')
    with op.batch_alter_table('docket_week_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docket_week_result_week_id'))
        batch_op.drop_index(batch_op.f('ix_docket_week_result_user_id'))

    op.drop_table('docket_week_result')
    with op.batch_alter_table('docket_tiebreaker_prediction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docket_tiebreaker_prediction_week_id'))
        batch_op.drop_index(batch_op.f('ix_docket_tiebreaker_prediction_user_id'))

    op.drop_table('docket_tiebreaker_prediction')
    # ### end Alembic commands ###
