"""cfb: add is_no_contest to cfb_game

Revision ID: 05b404d98dbd
Revises: fcf62a1207e9
Create Date: 2026-06-10 11:22:09.269829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b404d98dbd'
down_revision = 'fcf62a1207e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfb_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_no_contest', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfb_game', schema=None) as batch_op:
        batch_op.drop_column('is_no_contest')

    # ### end Alembic commands ###
