"""add cfb_week.last_reminder_type reminder de-dup flag

Revision ID: 1366fc218de3
Revises: 3e7e674c4d5b
Create Date: 2026-08-21 14:17:24.841506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1366fc218de3'
down_revision = '3e7e674c4d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfb_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reminder_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfb_week', schema=None) as batch_op:
        batch_op.drop_column('last_reminder_type')

    # ### end Alembic commands ###
