"""golf: drop unused is_alternate from golf_tournament_field

Revision ID: 1816342926ce
Revises: 1dbde6204bc2
Create Date: 2026-07-01 16:04:41.503204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1816342926ce'
down_revision = '1dbde6204bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golf_tournament_field', schema=None) as batch_op:
        batch_op.drop_column('is_alternate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golf_tournament_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_alternate', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
