"""golf tournament last_reminder_type for reminder de-dup

Revision ID: 1dbde6204bc2
Revises: 683bff36f66e
Create Date: 2026-07-01 12:13:24.947141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbde6204bc2'
down_revision = '683bff36f66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golf_tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reminder_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golf_tournament', schema=None) as batch_op:
        batch_op.drop_column('last_reminder_type')

    # ### end Alembic commands ###
