"""cfb week outcome snapshot

Revision ID: 24ef161df36a
Revises: 05b404d98dbd
Create Date: 2026-06-10 14:13:20.121823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ef161df36a'
down_revision = '05b404d98dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfb_week_outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lives_remaining', sa.Integer(), nullable=False),
    sa.Column('is_eliminated', sa.Boolean(), nullable=False),
    sa.Column('lost_life', sa.Boolean(), nullable=False),
    sa.Column('no_pick', sa.Boolean(), nullable=False),
    sa.Column('revived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['cfb_week.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'user_id', name='unique_cfb_week_outcome')
    )
    with op.batch_alter_table('cfb_week_outcome', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfb_week_outcome_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cfb_week_outcome_week_id'), ['week_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfb_week_outcome', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfb_week_outcome_week_id'))
        batch_op.drop_index(batch_op.f('ix_cfb_week_outcome_user_id'))

    op.drop_table('cfb_week_outcome')
    # ### end Alembic commands ###
