"""add docket_week and docket_game

Revision ID: 39cbbef16b24
Revises: 1816342926ce
Create Date: 2026-08-11 16:48:25.559838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cbbef16b24'
down_revision = '1816342926ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docket_week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=False),
    sa.Column('tiebreaker_game_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tiebreaker_game_id'], ['docket_game.id'], name='fk_docket_week_tiebreaker_game', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_number')
    )
    op.create_table('docket_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=40), nullable=False),
    sa.Column('api_event_id', sa.String(length=64), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('kickoff', sa.DateTime(), nullable=False),
    sa.Column('kickoff_at_deadline', sa.DateTime(), nullable=True),
    sa.Column('home_spread', sa.Float(), nullable=True),
    sa.Column('spread_book', sa.String(length=40), nullable=True),
    sa.Column('spread_locked_at', sa.DateTime(), nullable=True),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.Column('total_book', sa.String(length=40), nullable=True),
    sa.Column('total_locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['docket_week.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_event_id')
    )
    with op.batch_alter_table('docket_game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docket_game_week_id'), ['week_id'], unique=False)

    # use_alter=True defers the cycle-breaking FK to an ALTER pass that
    # op.create_table never runs on PostgreSQL (SQLAlchemy omits it from
    # inline CREATE TABLE when the dialect supports ALTER) — without this
    # explicit create, the constraint silently would not exist in prod.
    # Plain form on purpose: this chain is Postgres-only past f99903200f45.
    op.create_foreign_key('fk_docket_week_tiebreaker_game', 'docket_week',
                          'docket_game', ['tiebreaker_game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # The tiebreaker FK is created via ALTER (use_alter breaks the
    # docket_week <-> docket_game cycle), so it must be dropped explicitly
    # before docket_game can go — autogenerate missed this.
    with op.batch_alter_table('docket_week', schema=None) as batch_op:
        batch_op.drop_constraint('fk_docket_week_tiebreaker_game',
                                 type_='foreignkey')

    with op.batch_alter_table('docket_game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docket_game_week_id'))

    op.drop_table('docket_game')
    op.drop_table('docket_week')
