"""docket: add DocketWeek.default_error_tenths

The week's default tiebreaker error in integer tenths (D20-eng):
|designated game's locked O/U total - actual combined score|, or 0 when that
game was ruled No Contest. The grading pass computes it already and, before
this, discarded it.

The season rollup needs it: any enrolled player with no result row for a
week is charged the week's default error, including weeks before a late
joiner enrolled (Grading Clarifications), so late joiners buy no advantage
on ranking key 3.

Nullable rather than defaulted, because there is no correct constant. 0
means "the designated game was thrown out" and would silently forgive a
real week; any other value would be invented. NULL means "not graded yet,"
which is exactly true of every existing row.

No backfill is possible in SQL (the value depends on the designated game's
locked total and final score). None is needed either: prod docket tables are
empty until the Tue Sep 1 Week-1 import. A dev database holding weeks graded
before this revision reads NULL, and `flask docket recalc` restamps them.
The season pass refuses such a week loudly rather than dropping it from the
ledger, since a silently absent week changes everyone's ranks.

Downgrade is clean: the column is derived, and re-running the grading pass
recomputes it.

Revision ID: 3e7e674c4d5b
Revises: 6063041a3067
Create Date: 2026-08-13 12:07:59.059887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7e674c4d5b'
down_revision = '6063041a3067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docket_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_error_tenths', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docket_week', schema=None) as batch_op:
        batch_op.drop_column('default_error_tenths')

    # ### end Alembic commands ###
