"""add docket_enrollment

Revision ID: 4088a03c16ce
Revises: 04298e2415e9
Create Date: 2026-08-12 10:13:29.895106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4088a03c16ce'
down_revision = '04298e2415e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docket_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('has_paid', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season_year', name='uq_docket_enrollment_user_season')
    )
    with op.batch_alter_table('docket_enrollment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docket_enrollment_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docket_enrollment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docket_enrollment_user_id'))

    op.drop_table('docket_enrollment')
    # ### end Alembic commands ###
