"""add golf_tournament recap_email_sent flag

Revision ID: 4bcfd710a229
Revises: c65c548ea245
Create Date: 2026-03-14 21:24:46.031547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcfd710a229'
down_revision = 'c65c548ea245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golf_tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recap_email_sent', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golf_tournament', schema=None) as batch_op:
        batch_op.drop_column('recap_email_sent')

    # ### end Alembic commands ###
