"""docket: add DocketWeek.last_reminder_tier for D24 reminder de-dup

Revision ID: 6063041a3067
Revises: 6949297bdfd0
Create Date: 2026-08-12 19:49:32.609274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6063041a3067'
down_revision = '6949297bdfd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docket_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reminder_tier', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docket_week', schema=None) as batch_op:
        batch_op.drop_column('last_reminder_tier')

    # ### end Alembic commands ###
