"""golf major cut/DQ penalty tracking

Revision ID: 683bff36f66e
Revises: bf09572e2004
Create Date: 2026-07-01 10:30:14.329203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683bff36f66e'
down_revision = 'bf09572e2004'
branch_labels = None
depends_on = None


def upgrade():
    # NOT NULL columns carry a server_default so any existing golf_enrollment /
    # golf_pick rows backfill to 0 / false (major cut/DQ penalty tracking, ADR-034).
    with op.batch_alter_table('golf_enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'penalty_paid', sa.Integer(), nullable=False, server_default=sa.text('0')
        ))

    with op.batch_alter_table('golf_pick', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'penalty_triggered', sa.Boolean(), nullable=False, server_default=sa.false()
        ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golf_pick', schema=None) as batch_op:
        batch_op.drop_column('penalty_triggered')

    with op.batch_alter_table('golf_enrollment', schema=None) as batch_op:
        batch_op.drop_column('penalty_paid')

    # ### end Alembic commands ###
