"""add docket_line_correction audit table

D18's evidence row: one per audited pre-deadline correction of a locked
line, carrying old and new value plus bookmaker, who ruled it, why, and how
many picks had to be re-snapshotted onto the corrected number. The
re-snapshot is what makes the audit necessary — a pick grades on its own
line_value, so without this row a changed pick would look like drift.

``created_at`` is nullable to match the model's Python-side default, the
same shape every other docket audit timestamp uses.

Revision ID: 6949297bdfd0
Revises: b60fec9363dd
Create Date: 2026-08-12 17:41:40.506353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6949297bdfd0'
down_revision = 'b60fec9363dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docket_line_correction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('old_value', sa.Float(), nullable=False),
    sa.Column('old_book', sa.String(length=40), nullable=False),
    sa.Column('new_value', sa.Float(), nullable=False),
    sa.Column('new_book', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('picks_resnapshotted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['docket_game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('docket_line_correction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docket_line_correction_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_docket_line_correction_game_id'), ['game_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docket_line_correction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docket_line_correction_game_id'))
        batch_op.drop_index(batch_op.f('ix_docket_line_correction_admin_user_id'))

    op.drop_table('docket_line_correction')
    # ### end Alembic commands ###
