"""add avatar_emoji to users

Revision ID: 6ca93808bcd2
Revises: 8c282ed0beac
Create Date: 2026-04-12 09:35:09.859346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca93808bcd2'
down_revision = '8c282ed0beac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_emoji', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_emoji')

    # ### end Alembic commands ###
