"""add docket sheet receipt (one receipt per sitting, Brad 2026-10-02, ADR-070)

Revision ID: 8a05e7e5c96f
Revises: 8d3f6b1a2c95
Create Date: 2026-10-02 13:16:44.169926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a05e7e5c96f'
down_revision = '8d3f6b1a2c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docket_sheet_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('touched_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['docket_week.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_id', name='uq_docket_sheet_receipt_user_week')
    )
    with op.batch_alter_table('docket_sheet_receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docket_sheet_receipt_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_docket_sheet_receipt_week_id'), ['week_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docket_sheet_receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docket_sheet_receipt_week_id'))
        batch_op.drop_index(batch_op.f('ix_docket_sheet_receipt_user_id'))

    op.drop_table('docket_sheet_receipt')
    # ### end Alembic commands ###
