"""add is_admin to golf_enrollment

Revision ID: 8c282ed0beac
Revises: bd07defd2be6
Create Date: 2026-04-11 10:36:31.806398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c282ed0beac'
down_revision = 'bd07defd2be6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('golf_enrollment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golf_enrollment', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
