"""add golf pick em models

Revision ID: 9744be4c108a
Revises: a6bd9748bf4d
Create Date: 2026-03-05 22:14:13.090373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9744be4c108a'
down_revision = 'a6bd9748bf4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('golf_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_player_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_amateur', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_player_id')
    )
    op.create_table('golf_tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_tourn_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('pick_deadline', sa.DateTime(), nullable=True),
    sa.Column('purse', sa.Integer(), nullable=True),
    sa.Column('is_team_event', sa.Boolean(), nullable=True),
    sa.Column('is_major', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('results_finalized', sa.Boolean(), nullable=True),
    sa.Column('picks_open_notified', sa.Boolean(), nullable=True),
    sa.Column('field_alert_sent', sa.Boolean(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_tourn_id', 'season_year', name='unique_golf_tournament_per_season')
    )
    op.create_table('golf_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('has_paid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season_year', name='unique_golf_enrollment')
    )
    with op.batch_alter_table('golf_enrollment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_golf_enrollment_user_id'), ['user_id'], unique=False)

    op.create_table('golf_pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('primary_player_id', sa.Integer(), nullable=False),
    sa.Column('backup_player_id', sa.Integer(), nullable=False),
    sa.Column('active_player_id', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('primary_used', sa.Boolean(), nullable=True),
    sa.Column('backup_used', sa.Boolean(), nullable=True),
    sa.Column('admin_override', sa.Boolean(), nullable=True),
    sa.Column('admin_override_note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['active_player_id'], ['golf_player.id'], ),
    sa.ForeignKeyConstraint(['backup_player_id'], ['golf_player.id'], ),
    sa.ForeignKeyConstraint(['primary_player_id'], ['golf_player.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['golf_tournament.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tournament_id', name='unique_golf_user_tournament_pick')
    )
    with op.batch_alter_table('golf_pick', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_golf_pick_tournament_id'), ['tournament_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_golf_pick_user_id'), ['user_id'], unique=False)

    op.create_table('golf_season_player_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['golf_player.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'player_id', 'season_year', name='unique_golf_player_usage')
    )
    with op.batch_alter_table('golf_season_player_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_golf_season_player_usage_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_golf_season_player_usage_user_id'), ['user_id'], unique=False)

    op.create_table('golf_tournament_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('is_alternate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['golf_player.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['golf_tournament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'player_id', name='unique_golf_player_tournament_field')
    )
    with op.batch_alter_table('golf_tournament_field', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_golf_tournament_field_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_golf_tournament_field_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('golf_tournament_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('final_position', sa.String(length=20), nullable=True),
    sa.Column('earnings', sa.Integer(), nullable=True),
    sa.Column('rounds_completed', sa.Integer(), nullable=True),
    sa.Column('score_to_par', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['golf_player.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['golf_tournament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'player_id', name='unique_golf_player_tournament_result')
    )
    with op.batch_alter_table('golf_tournament_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_golf_tournament_result_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_golf_tournament_result_tournament_id'), ['tournament_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golf_tournament_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_golf_tournament_result_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_golf_tournament_result_player_id'))

    op.drop_table('golf_tournament_result')
    with op.batch_alter_table('golf_tournament_field', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_golf_tournament_field_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_golf_tournament_field_player_id'))

    op.drop_table('golf_tournament_field')
    with op.batch_alter_table('golf_season_player_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_golf_season_player_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_golf_season_player_usage_player_id'))

    op.drop_table('golf_season_player_usage')
    with op.batch_alter_table('golf_pick', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_golf_pick_user_id'))
        batch_op.drop_index(batch_op.f('ix_golf_pick_tournament_id'))

    op.drop_table('golf_pick')
    with op.batch_alter_table('golf_enrollment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_golf_enrollment_user_id'))

    op.drop_table('golf_enrollment')
    op.drop_table('golf_tournament')
    op.drop_table('golf_player')
    # ### end Alembic commands ###
