"""add announcements drafts and sent archive

Revision ID: aca46ca62591
Revises: f3a7c2d9e815
Create Date: 2026-09-24 10:31:14.739425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca46ca62591'
down_revision = 'f3a7c2d9e815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('preheader', sa.String(length=200), nullable=True),
    sa.Column('cta', sa.String(length=16), nullable=False),
    sa.Column('audiences', sa.String(length=64), nullable=False),
    sa.Column('recipient_filter', sa.String(length=8), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('sent_html', sa.Text(), nullable=True),
    sa.Column('sent_plain', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_sent_at'), ['sent_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_sent_at'))
        batch_op.drop_index(batch_op.f('ix_announcements_created_by_id'))

    op.drop_table('announcements')
    # ### end Alembic commands ###
