"""add World Cup Fantasy Pool models

Revision ID: bd07defd2be6
Revises: f38ecaec8224
Create Date: 2026-04-04 02:47:56.953117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd07defd2be6'
down_revision = 'f38ecaec8224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worldcup_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fifa_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('confederation', sa.String(length=10), nullable=False),
    sa.Column('group_letter', sa.String(length=1), nullable=False),
    sa.Column('is_eliminated', sa.Boolean(), nullable=True),
    sa.Column('group_wins', sa.Integer(), nullable=True),
    sa.Column('group_draws', sa.Integer(), nullable=True),
    sa.Column('group_losses', sa.Integer(), nullable=True),
    sa.Column('advancement_method', sa.String(length=20), nullable=True),
    sa.Column('best_finish', sa.String(length=20), nullable=True),
    sa.Column('base_points', sa.Float(), nullable=True),
    sa.Column('multiplied_points', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fifa_code')
    )
    op.create_table('worldcup_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('has_paid', sa.Boolean(), nullable=True),
    sa.Column('picks_submitted', sa.Boolean(), nullable=True),
    sa.Column('usa_goals_guess', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season_year', name='unique_worldcup_enrollment')
    )
    with op.batch_alter_table('worldcup_enrollment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worldcup_enrollment_user_id'), ['user_id'], unique=False)

    op.create_table('worldcup_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('group_letter', sa.String(length=1), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('is_draw', sa.Boolean(), nullable=True),
    sa.Column('extra_time', sa.Boolean(), nullable=True),
    sa.Column('penalties', sa.Boolean(), nullable=True),
    sa.Column('kickoff_utc', sa.DateTime(), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['worldcup_team.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['worldcup_team.id'], ),
    sa.ForeignKeyConstraint(['winner_team_id'], ['worldcup_team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_number')
    )
    with op.batch_alter_table('worldcup_match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worldcup_match_stage'), ['stage'], unique=False)

    op.create_table('worldcup_pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('base_points', sa.Float(), nullable=True),
    sa.Column('multiplied_points', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['worldcup_enrollment.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['worldcup_team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'team_id', name='unique_worldcup_enrollment_team_pick')
    )
    with op.batch_alter_table('worldcup_pick', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worldcup_pick_enrollment_id'), ['enrollment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worldcup_pick', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worldcup_pick_enrollment_id'))

    op.drop_table('worldcup_pick')
    with op.batch_alter_table('worldcup_match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worldcup_match_stage'))

    op.drop_table('worldcup_match')
    with op.batch_alter_table('worldcup_enrollment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worldcup_enrollment_user_id'))

    op.drop_table('worldcup_enrollment')
    op.drop_table('worldcup_team')
    # ### end Alembic commands ###
