"""add home_pen away_pen to worldcup_match

Revision ID: bf09572e2004
Revises: f00267f4779e
Create Date: 2026-06-30 10:26:43.327701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf09572e2004'
down_revision = 'f00267f4779e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worldcup_match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_pen', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_pen', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worldcup_match', schema=None) as batch_op:
        batch_op.drop_column('away_pen')
        batch_op.drop_column('home_pen')

    # ### end Alembic commands ###
