"""add CFB Survivor models

Revision ID: c65c548ea245
Revises: 9744be4c108a
Create Date: 2026-03-06 17:45:20.266140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65c548ea245'
down_revision = '9744be4c108a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfb_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('conference', sa.String(length=50), nullable=True),
    sa.Column('national_title_odds', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cfb_week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('is_playoff_week', sa.Boolean(), nullable=True),
    sa.Column('round_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_number')
    )
    op.create_table('cfb_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('lives_remaining', sa.Integer(), nullable=True),
    sa.Column('is_eliminated', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('has_paid', sa.Boolean(), nullable=True),
    sa.Column('cumulative_spread', sa.Float(), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season_year', name='unique_cfb_enrollment')
    )
    with op.batch_alter_table('cfb_enrollment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfb_enrollment_user_id'), ['user_id'], unique=False)

    op.create_table('cfb_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_team_name', sa.String(length=100), nullable=True),
    sa.Column('away_team_name', sa.String(length=100), nullable=True),
    sa.Column('home_team_spread', sa.Float(), nullable=True),
    sa.Column('game_time', sa.DateTime(), nullable=True),
    sa.Column('home_team_won', sa.Boolean(), nullable=True),
    sa.Column('api_event_id', sa.String(length=64), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('spread_locked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['cfb_team.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['cfb_team.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['cfb_week.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cfb_game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfb_game_api_event_id'), ['api_event_id'], unique=False)

    op.create_table('cfb_pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['cfb_team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['week_id'], ['cfb_week.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_id', name='unique_cfb_user_week_pick')
    )
    with op.batch_alter_table('cfb_pick', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfb_pick_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cfb_pick_week_id'), ['week_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfb_pick', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfb_pick_week_id'))
        batch_op.drop_index(batch_op.f('ix_cfb_pick_user_id'))

    op.drop_table('cfb_pick')
    with op.batch_alter_table('cfb_game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfb_game_api_event_id'))

    op.drop_table('cfb_game')
    with op.batch_alter_table('cfb_enrollment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfb_enrollment_user_id'))

    op.drop_table('cfb_enrollment')
    op.drop_table('cfb_week')
    op.drop_table('cfb_team')
    # ### end Alembic commands ###
