"""add sync_runs (one row per scheduled job run; the admin dashboard's Jobs list)

Revision ID: cac4d3e60af5
Revises: b7c4e2a91d05
Create Date: 2026-09-28 14:12:53.716030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac4d3e60af5'
down_revision = 'b7c4e2a91d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('odds_credits_remaining', sa.Integer(), nullable=True),
    sa.Column('via', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index('ix_sync_runs_job_started_at', ['job', 'started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_runs_job_started_at')

    op.drop_table('sync_runs')
    # ### end Alembic commands ###
