"""add phone to users

Revision ID: d44ccf51e702
Revises: 9c8c3a0e41d8
Create Date: 2026-05-26 10:47:48.398113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44ccf51e702'
down_revision = '9c8c3a0e41d8'
branch_labels = None
depends_on = None


def upgrade():
    """Add the nullable ``phone`` column to ``users``."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    """Drop the ``phone`` column from ``users``."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
