"""add season_finishes, the club permanent record

Revision ID: e0cee073fa75
Revises: cac4d3e60af5
Create Date: 2026-09-28 17:02:52.917194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cee073fa75'
down_revision = 'cac4d3e60af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_finishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=20), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('place', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('field_size', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game', 'season_year', 'name', name='uq_season_finish_game_year_name')
    )
    with op.batch_alter_table('season_finishes', schema=None) as batch_op:
        batch_op.create_index('ix_season_finish_game_year', ['game', 'season_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_season_finishes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season_finishes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_finishes_user_id'))
        batch_op.drop_index('ix_season_finish_game_year')

    op.drop_table('season_finishes')
    # ### end Alembic commands ###
