"""add commish_notes editable home note

Revision ID: f00267f4779e
Revises: 24ef161df36a
Create Date: 2026-06-15 10:33:11.017491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00267f4779e'
down_revision = '24ef161df36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commish_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commish_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commish_notes_state'), ['state'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commish_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commish_notes_state'))

    op.drop_table('commish_notes')
    # ### end Alembic commands ###
