"""add cfb_week recap_email_sent flag

Revision ID: f38ecaec8224
Revises: 4bcfd710a229
Create Date: 2026-03-14 22:05:32.286815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38ecaec8224'
down_revision = '4bcfd710a229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfb_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recap_email_sent', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cfb_week', schema=None) as batch_op:
        batch_op.drop_column('recap_email_sent')

    # ### end Alembic commands ###
