"""worldcup api id columns

Revision ID: fcf62a1207e9
Revises: f99903200f45
Create Date: 2026-06-02 12:46:25.524647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf62a1207e9'
down_revision = 'f99903200f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worldcup_match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_fixture_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_worldcup_match_api_fixture_id'), ['api_fixture_id'], unique=False)

    with op.batch_alter_table('worldcup_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_team_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worldcup_team', schema=None) as batch_op:
        batch_op.drop_column('api_team_id')

    with op.batch_alter_table('worldcup_match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worldcup_match_api_fixture_id'))
        batch_op.drop_column('api_fixture_id')

    # ### end Alembic commands ###
